version: '3'
services:
   autodesk-lm:
    build: /
    hostname: server
    restart: always
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - /opt/licenses:/tmp/licenses
